name: pipeline
on:
  push:
    branches: [ master ]
  pull_request:
jobs:
  go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with: { go-version: '^1.14' }
    - run: go mod download
    - run: make check-go
    - run: go test -race -coverprofile=coverage.txt ./...
    # Dhill: disabled this since it's not important for our fork
    # - uses: codecov/codecov-action@v1
    #   with:
    #     file: ./coverage.txt
    #     fail_ci_if_error: true

  web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with: { node-version: '12' }
    - run: npm install
      working-directory: web
    - run: npm run lint
      working-directory: web
